### ISSUE TITLE
Wrong/Dead Link

### ISSUE THREAD

**Issue by ajmeese7** [dwyl/phoenix-liveview-todo-list-tutorial#16]
The link in this sentence is for the counter tutorial project:
> 💡 You can also try the version deployed to Heroku: https://live-view-counter.herokuapp.com

And the link presented in the project details, https://liveview-todo.herokuapp.com/, is showing `Internal Server Error` every time I attempt to visit it. Did you perhaps mean to include https://live-view-todo.herokuapp.com/ instead? That link works as expected.

Also I think this portion needs to be removed as well, it is also only applicable to the counter tutorial:
> 💡 Open a second browser window (e.g. incognito mode), you will see the the counter updating in both places like magic!

**Comment by nelsonic** [comment]
@ajmeese7 thank you for opening this issue. 🙌
You’re correct, the link to the heroku app needs to be updated. 👍🏻 (If you have time, please PR the fix)

As for the section on opening a second browser window, that should be “TODO” (feature to be added) on the backlog of this tutorial. We would like to sync the todo list items between people using the list. 💭

**Comment by nelsonic** [comment]
Hi @ajmeese7, Thanks again for opening this issue. 👍 
https://liveview-todo.herokuapp.com/ has been working consistently since #18  🚀 
![image](https://user-images.githubusercontent.com/194400/144274240-bfda4dbd-6759-4dab-9066-4b72ad13201f.png)

Closing. ✅
