### ISSUE TITLE
Update to Phoenix 1.6

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-todo-list-tutorial#18]
The application returns a server error at the moment on Heroku:
![image](https://user-images.githubusercontent.com/6057298/138887589-a82da697-26f5-4525-8747-c40f5a9efb5a.png)

I think updating the project to Phoenix 1.6 might fix this issue

**Comment by nelsonic** [comment]
This is working as expected. (Thanks again @SimonLab)

![image](https://user-images.githubu✅ ontent.com/194400/144274092-5ac4ca0c-9a6b-4d5e-8935-8bc76f528947.png)

Closing. :whi
