### ISSUE TITLE
The app is not working 

### ISSUE THREAD

**Issue by chintan9** [dwyl/phoenix-liveview-todo-list-tutorial#3]
The app is not working  

https://todolist.gigalixirapp.com/ 

I forked repo and published app over gigalixir.com and did not work

**Comment by nelsonic** [comment]
Hi @chintan9 What part is not working? 🤷‍♂️ 

Please try the heroku version: https://liveview-todo.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/96385470-0f04d280-118c-11eb-9e1c-1080be189443.png)

The _basic_ functionality should all be working. 💭 

As per the `README.md` we have a `TODO` (`#HelpWanted`) section requesting help for the last 3 pieces of functionality: 
[https://github.com/dwyl/phoenix-liveview-todo-list-tutorial#todo-finish-the-tutorial-helpwanted](https://github.com/dwyl/phoenix-liveview-todo-list-tutorial/tree/0e2a574d8182b2ddc01e5c2009b43487a656e82a#todo-finish-the-tutorial-helpwanted)

P.S: how did you find this repository?

**Comment by chintan9** [comment]
@nelsonic  I am getting websocket error.  I use https://www.gigalixir.com since it has nice feature for elixir. I found you code via github search.

**Comment by nelsonic** [comment]
@chintan9 thanks for confirming that it's working for you. 👍
