### ISSUE TITLE
Live Components

### ISSUE THREAD

**Issue by SimonLab** [dwyl/phoenix-liveview-todo-list-tutorial#69]
So far in this tutorial we have put all the template code into a single file:
[`/lib/live_view_todo_web/live/page_live.html.heex`](https://github.com/dwyl/phoenix-liveview-todo-list-tutorial/blob/0a0c19f31808bc8f8eaa3d57e4afdb07be0bd6bf/lib/live_view_todo_web/live/page_live.html.heex)
That is "OK" in a mini project like this, but it will quickly become unmaintainable in a larger `LiveView` codebase.
We are therefore going to _proactively_ migrate the templates to using `Phoenix `LiveComponents`.

see https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html

Check the heex file https://github.com/dwyl/phoenix-liveview-todo-list-tutorial/blob/main/lib/live_view_todo_web/live/page_live.html.heex
to see which parts can be extracted to its own component.

This heex file is not big, however creating a component will be used as an example on how to do it for bigger files.

**Comment by SimonLab** [comment]
check dependencies `mix hex.outdated`:
![image](https://user-images.githubusercontent.com/6057298/203943449-778510d9-a8b9-4061-9a4d-a732792f446a.png)

Updating `phoenix_live_view` to 0.18 will create some breaking changes. I'll start by fixing those

**Comment by SimonLab** [comment]
Warnings and error after updating dependencies:
![image](https://user-images.githubusercontent.com/6057298/204235556-6b3c0297-c890-42e7-868e-ed2fa90424cc.png)

**Comment by nelsonic** [comment]
Fixed. ✅
